// src/components/card/card.tsx
import * as React from 'react';
import cn from 'classnames';
import { CardProps } from '../../../dist/meta/react';

const Card: React.FC<CardProps> = ({
  textAlign = 'left',
  children,
  cardBody,
  cardSubTitle,
  cardTitle,
  imgSrc,
}: CardProps) => {
  const classes = cn('card', `text-${textAlign}`, {});
  return (
    <div className={classes}>
      {imgSrc && (
        <img
          alt="An example displayed inside a Bootstrap-themed card"
          src={imgSrc}
          className="card-img-top"
        />
      )}
      <div className="card-body">
        <h5 className="card-title">{cardTitle}</h5>
        {cardSubTitle && (
          <h6 className="card-subtitle mb-2 text-muted">{cardSubTitle}</h6>
        )}
        <p className="card-text">{cardBody}</p>
        {children}
      </div>
    </div>
  );
};

export default Card;

// src/components/card/card.vue
<template>
  <div
    v-bind:class="[
      'card',
      {
        [`text-${textAlign}`]: true,
      },
    ]"
  >
    <img :src="imgSrc" class="card-img-top" alt="image alt" />

    <div class="card-body">
      <h5 class="card-title" v-if="cardTitle">{{ cardTitle }}</h5>
      <p class="card-text">
        <slot></slot>
      </p>
      <slot name="footer"></slot>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    imgSrc: String,
    cardTitle: {
      type: String,
      required: true,
    },
    /**
     * @values left, center, right
     */
    textAlign: {
      type: String,
      default: 'left',
      required: false,
    },
  },
};
</script>

<style scoped lang="scss">
.card {
}
</style>
